language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

script:
  - sbt ++2.11.7 scalastyle
  - sbt ++2.11.7 test:scalastyle
  - sbt ++2.11.7 coverage test
  - sbt ++2.11.7 coverageReport coverageAggregate
  - sbt ++2.11.7 codacyCoverage
